# Generated by Django 5.0.7 on 2024-12-24 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('analysis_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('result', models.CharField(blank=True, choices=[('real', 'Real'), ('fake', 'Fake')], max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
                ('fake_frame_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
